export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const UPDATE_RANGE = 'UPDATE_RANGE';
export const ADD_SELECT = 'ADD_SELECT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const UPDATE_COMMENTS_ARTICLE = 'UPDATE_COMMENTS_ARTICLE';

